/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomSheet: typeof import('./src/components/mobile/BottomSheet.vue')['default']
    BrandPage: typeof import('./src/components/settings/BrandPage.vue')['default']
    CameraScanner: typeof import('./src/components/mobile/CameraScanner.vue')['default']
    CartBar: typeof import('./src/components/mobile/CartBar.vue')['default']
    ChangePasswordDialog: typeof import('./src/components/settings/ChangePasswordDialog.vue')['default']
    CloseShift: typeof import('./src/components/Dialog/CloseShift.vue')['default']
    Customer: typeof import('./src/components/Customer.vue')['default']
    CustomerBar: typeof import('./src/components/pos/CustomerBar.vue')['default']
    CustomerForm: typeof import('./src/components/Dialog/CustomerForm.vue')['default']
    FieldControl: typeof import('./src/components/form/FieldControl.vue')['default']
    FieldLayoutEditor: typeof import('./src/components/layout-editor/FieldLayoutEditor.vue')['default']
    FieldSettings: typeof import('./src/components/layout-editor/FieldSettings.vue')['default']
    Held: typeof import('./src/components/Dialog/Held.vue')['default']
    ImageUploader: typeof import('./src/components/Controls/ImageUploader.vue')['default']
    Invoice: typeof import('./src/components/Invoice.vue')['default']
    InvoicePicker: typeof import('./src/components/pos/InvoicePicker.vue')['default']
    InvoicePickerBody: typeof import('./src/components/pos/InvoicePickerBody.vue')['default']
    Item: typeof import('./src/components/Item.vue')['default']
    ItemCard: typeof import('./src/components/pos/ItemCard.vue')['default']
    ItemCatalog: typeof import('./src/components/pos/ItemCatalog.vue')['default']
    ItemDetail: typeof import('./src/components/ItemDetail.vue')['default']
    ItemSelector: typeof import('./src/components/ItemSelector.vue')['default']
    LayoutEditorModal: typeof import('./src/components/layout-editor/LayoutEditorModal.vue')['default']
    LayoutForm: typeof import('./src/components/form/LayoutForm.vue')['default']
    LinkControl: typeof import('./src/components/form/LinkControl.vue')['default']
    MobileTabBar: typeof import('./src/components/mobile/MobileTabBar.vue')['default']
    MobileTopBar: typeof import('./src/components/mobile/MobileTopBar.vue')['default']
    MoreSheet: typeof import('./src/components/mobile/MoreSheet.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    OpenShift: typeof import('./src/components/Dialog/Open-Shift.vue')['default']
    PaneResizer: typeof import('./src/components/PaneResizer.vue')['default']
    Payment: typeof import('./src/components/Payment.vue')['default']
    PosProfileCard: typeof import('./src/components/PosProfileCard.vue')['default']
    PosProfilePage: typeof import('./src/components/settings/PosProfilePage.vue')['default']
    PreferencesPage: typeof import('./src/components/settings/PreferencesPage.vue')['default']
    ProfilePage: typeof import('./src/components/settings/ProfilePage.vue')['default']
    Return: typeof import('./src/components/Dialog/Return.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaleModeBar: typeof import('./src/components/pos/SaleModeBar.vue')['default']
    Settings: typeof import('./src/components/Dialog/Settings.vue')['default']
    SettingsPageLayout: typeof import('./src/components/settings/SettingsPageLayout.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SidebarLink: typeof import('./src/components/SidebarLink.vue')['default']
    ThemePreview: typeof import('./src/components/settings/ThemePreview.vue')['default']
    ThemeSelector: typeof import('./src/components/settings/ThemeSelector.vue')['default']
    TotalsReadout: typeof import('./src/components/pos/TotalsReadout.vue')['default']
  }
}
